"""Generate src/analysis/aliases.ts from the committed Python alias table.

The table is hand-maintained YAML in `src/precedent/data/passthrough_aliases.yaml` and it is
the source of truth. A Worker cannot read a file or parse YAML at runtime, so it ships as a
TypeScript module - generated, never edited, and checked by a test that regenerates it and
compares. Two hand-maintained copies of an entity table would drift, and the drift would be
invisible: the site and the tool would cluster the same auditor's spelling differently and
both would look right.

    python scripts/generate_aliases.py
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "src" / "precedent" / "data" / "passthrough_aliases.yaml"
TARGET = Path(__file__).resolve().parents[1] / "src" / "analysis" / "aliases.ts"

HEADER = """/**
 * Pass-through entity aliases.
 *
 * GENERATED from `src/precedent/data/passthrough_aliases.yaml` by
 * `awards/scripts/generate_aliases.py`. Do not edit this file: edit the YAML and regenerate.
 * `test/aliases.test.ts` fails if the two drift, because a site and a tool that cluster the
 * same auditor's spelling differently would both look right.
 *
 * Every entry here was decided by a person. Nothing is inferred, and an initialism is only
 * ever resolved through this table - the same three letters name a different agency in
 * another state.
 */

export interface AliasEntry {
  canonical: string;
  state: string;
  entityType: string | null;
  ein: string | null;
  aliases: string[];
}

export const ALIAS_TABLE: AliasEntry[] = """


def main() -> int:
    rows = yaml.safe_load(SOURCE.read_text(encoding="utf-8")) or []
    entries = [
        {
            "canonical": str(r["canonical"]).strip(),
            "state": str(r["state"]).strip().upper(),
            "entityType": r.get("entity_type"),
            "ein": r.get("ein"),
            "aliases": list(r.get("aliases") or []),
        }
        for r in rows
    ]
    body = json.dumps(entries, indent=2, ensure_ascii=False)
    TARGET.write_text(HEADER + body + ";\n", encoding="utf-8", newline="\n")
    print(f"{len(entries)} entities -> {TARGET.relative_to(Path.cwd())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
