/**
 * Pass-through entity aliases.
 *
 * GENERATED from `src/precedent/data/passthrough_aliases.yaml` by
 * `awards/scripts/generate_aliases.py`. Do not edit this file: edit the YAML and regenerate.
 * `test/aliases.test.ts` fails if the two drift, because a site and a tool that cluster the
 * same auditor's spelling differently would both look right.
 *
 * Every entry here was decided by a person. Nothing is inferred, and an initialism is only
 * ever resolved through this table - the same three letters name a different agency in
 * another state.
 */

export interface AliasEntry {
  canonical: string;
  state: string;
  entityType: string | null;
  ein: string | null;
  aliases: string[];
}

export const ALIAS_TABLE: AliasEntry[] = [
  {
    "canonical": "OHIO DEPARTMENT OF AGING",
    "state": "OH",
    "entityType": "state_agency",
    "ein": null,
    "aliases": [
      "OHIO DEPT OF AGING",
      "STATE OF OHIO DEPARTMENT OF AGING",
      "OHIO DEPARTMENT ON AGING",
      "ODA",
      "OHIO DEPARTMENT OF AGING (ODA)"
    ]
  },
  {
    "canonical": "BUCKEYE HILLS REGIONAL COUNCIL",
    "state": "OH",
    "entityType": "regional_council",
    "ein": null,
    "aliases": [
      "BUCKEYE HILLS HOCKING VALLEY REGIONAL DEVELOPMENT DISTRICT",
      "BUCKEYE HILLS REGIONAL COUNCIL AREA AGENCY ON AGING 8",
      "BUCKEYE HILLS AREA AGENCY ON AGING"
    ]
  },
  {
    "canonical": "COUNCIL ON AGING OF SOUTHWESTERN OHIO",
    "state": "OH",
    "entityType": "nonprofit",
    "ein": null,
    "aliases": [
      "COUNCIL ON AGING SOUTHWESTERN OHIO",
      "CINCINNATI COUNCIL OF AGING",
      "COUNCIL ON AGING OF SOUTHWESTERN OHIO AREA AGENCY ON AGING 1"
    ]
  },
  {
    "canonical": "AREA OFFICE ON AGING OF NORTHWESTERN OHIO",
    "state": "OH",
    "entityType": "nonprofit",
    "ein": null,
    "aliases": [
      "AREA OFFICE ON AGING OF NORTHWEST OHIO",
      "AREA OFFICE ON AGING OF NORTHWEST OHIO, INC.",
      "AREA AGENCY ON AGING 4"
    ]
  },
  {
    "canonical": "OHIO DISTRICT 5 AREA AGENCY ON AGING",
    "state": "OH",
    "entityType": "nonprofit",
    "ein": null,
    "aliases": [
      "OHIO DISTRICT 5 AREA AGENCY ON AGING, INC.",
      "DISTRICT 5 AREA AGENCY ON AGING",
      "AREA AGENCY ON AGING DISTRICT 5"
    ]
  }
];
